# github action to build dockerfile in root of repo and push to ghcr with username krazysh01 and tag palworldserver
# https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: Build and Deploy PalworldServer
on:
  push:
    branches: [palworld]
  pull_request:
    branches: [palworld]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/krazysh01/palworldserver:latest
